### ISSUE TITLE
Cross-device mapping

### ISSUE THREAD

**Issue by b0xtch** [evilsocket/llama3-cake#2]
- add support for cross-GPU device mapping

Related issue/feature:
https://github.com/EricLBuehler/mistral.rs/issues/395

**Comment by evilsocket** [comment]
mind elaborating?

**Comment by b0xtch** [comment]
> mind elaborating?

https://github.com/evilsocket/llama3-cake/commit/c55c7056f6caf73c087d851f44adfe4895a07579

You've addressed it here nice
